parameters:
#    hockey_stats.example.class: HockeyStats\Bundle\Example

services:
#    hockey_stats.example:
#        class: %hockey_stats.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
